### ISSUE TITLE
Misc. suggestions

### ISSUE THREAD

**Issue by kieraneglin** [Schaka/crops-docker#1]
Hey there! I created an extremely similar repo before I realized this existed: https://github.com/kieraneglin/crops-docker

I thought I'd mention a few differences between ours that you can take if you so choose!

- Due to some user/group permissions in the Dockerfile and using `--user "crops:crops"` in the `Extra Parameters` section, my container doesn't need to run as root on Unraid
- My Dockerfile is set to always pull the latest version of the code in the chance there's ever an update
- You can change which repo/branch `crops` is pulled from via Docker build args
- My Dockerfile adds a `crops` binary so you can use commands like `crops -h` from within the container
- My image holds the container open because that's what I prefer - the app always stays alive in Unraid and I exec into it to run commands. Most people probably won't like that but I thought I'd mention

**Comment by Schaka** [comment]
Thank you. These are great changed. But I've decided to link to your repo as well as fertilizer in the readme.
I don't think I can justify maintaining it at this point since there are superior versions out there.
